{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.midgard.pc.tailscale;

  tailnets = concatStringsSep "|" (attrNames cfg.tailnets);

  tsScript = pkgs.writeShellApplication {
    name = "ts";
    runtimeInputs = with pkgs; [
      tailscale
      jq
      gnugrep
      xdg-utils
    ];
    text = ''
      tailscale_login() {
        local flags="--login-server=$1 --accept-routes"
        if [ -n "''${2:-}" ]; then
          flags="--authkey=$2 $flags"
        else
          flags="--force-reauth $flags"
        fi
        sudo tailscale up $flags 2>&1 | while IFS= read -r line; do
          echo "$line"
          url=$(echo "$line" | grep -oE 'https://[^ ]+' || true)
          if [ -n "$url" ]; then
            xdg-open "$url" 2>/dev/null &
          fi
        done
      }

      update_ssh_config() {
        local ssh_user="$1"
        local config_dir="$HOME/.ssh/config.d"
        local config_file="$config_dir/tailscale"
        mkdir -p "$config_dir"

        local peers
        peers=$(tailscale status --json 2>/dev/null \
          | jq -r '.Peer[] | select(.Online) | .HostName' 2>/dev/null) || true

        if [ -z "$peers" ]; then
          echo "No peers found, skipping SSH config generation"
          return
        fi

        {
          echo "# Generated by ts — do not edit"
          echo ""
          for host in $peers; do
            echo "Host $host"
            echo "  User $ssh_user"
            echo ""
          done
        } > "$config_file"
        echo "Updated $config_file ($ssh_user@{$(echo "$peers" | tr '\n' ',' | sed 's/,$//')})"

        local main_config="$HOME/.ssh/config"
        if [ -f "$main_config" ] && ! grep -q 'Include config.d/' "$main_config" 2>/dev/null; then
          sed -i '1s;^;Include config.d/*\n\n;' "$main_config"
          echo "Added 'Include config.d/*' to $main_config"
        elif [ ! -f "$main_config" ]; then
          echo "Include config.d/*" > "$main_config"
          echo "Created $main_config with 'Include config.d/*'"
        fi
      }

      case "''${1:-status}" in
        ${concatStringsSep "\n        " (mapAttrsToList (name: net:
          ''${name})
            ${if net.authKeyFile != null then ''
              AUTH_KEY=$(sudo cat ${net.authKeyFile} 2>/dev/null) || true
              if [ -z "$AUTH_KEY" ]; then
                echo "error: auth key not available at ${net.authKeyFile}" >&2
                exit 1
              fi
              tailscale_login "${net.loginServer}" "$AUTH_KEY"
            '' else ''
              tailscale_login "${net.loginServer}"
            ''}${optionalString (net.sshUser != null) ''
              update_ssh_config "${net.sshUser}"
            ''};;'') cfg.tailnets)}
        status)
          tailscale status
          ;;
        *)
          echo "usage: ts [${tailnets}|status]"
          ;;
      esac
    '';
  };
in
{
  options.midgard.pc.tailscale = {
    enable = mkEnableOption "Tailscale client with tailnet switcher";

    tailnets = mkOption {
      type = types.attrsOf (types.submodule {
        options = {
          loginServer = mkOption {
            type = types.str;
            description = "Full URL of the headscale/tailscale coordination server";
            example = "https://head.dev.fornybar.eviny.io";
          };
          authKeyFile = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "Path to a pre-auth key file. If set, uses authkey instead of OIDC browser flow.";
            example = "/run/secrets/tailscale-auth-key";
          };
          sshUser = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "If set, generates ~/.ssh/config.d/tailscale with this user for all peers after connecting.";
            example = "odin";
          };
        };
      });
      default = { };
      description = "Named tailnets available via the `ts` switcher command";
      example = literalExpression ''
        {
          dev = { loginServer = "https://head.dev.fornybar.eviny.io"; sshUser = "odin"; };
          prod = { loginServer = "https://head.fornybar.eviny.io"; sshUser = "odin"; };
        }
      '';
    };
  };

  config = mkIf cfg.enable {
    services.tailscale.enable = true;
    environment.systemPackages = [ tsScript ];
  };
}
